export const ERROR = 'ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const END_LOADING = 'END_LOADING';
export const START_LOADING = 'START_LOADING';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

